### ISSUE TITLE
ball_xy data in your code and after ball detector are different

### ISSUE THREAD

**Issue by ul611** [fenaux/soccer-applications#1]
Hello!

Thank you for your magnifique work.
I'm trying to reproduce the result, but after running the ball detector from roboflow repo (https://github.com/roboflow/sports/tree/main/examples/soccer) I'm getting totally different results for ball_xy data.
![image](https://github.com/user-attachments/assets/ad1c5e97-7c1a-458d-8096-f0a0a87390e4)

Could you please provide your data/2e57b9_0_ball.npy file?

Thanks in advance.

**Comment by fenaux** [comment]
Hi,

Please note the coordinates  corresponding to ball_xy are coordinates in the pitch frame.
Coordinates at the output of ball detector are in the image frame. So they need to be transformed 
transformed_xy = transformer.transform_points(points=xy) as done in run_ball_radar function

Anyway as you asked I uploaded the npy file. If you run run_ball_radar function with the same viedo you shouyld obtain this npy file

**Comment by ul611** [comment]
Thank you!
